name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  python-security:
    uses: project-unisonOS/.github/.github/workflows/reusable-python-security.yml@7b392529550f2963dc0022428e873ddb17cdedd4
    with:
      python-version: "3.12"
      working-directory: "."
      unison-common-ref: "8b82c2fe26b31aa4b368eb150654e0dd3561fa58"

  container-supply-chain:
    uses: project-unisonOS/.github/.github/workflows/reusable-container-supply-chain.yml@7b392529550f2963dc0022428e873ddb17cdedd4
    with:
      image-name: unison-storage
      dockerfile: Dockerfile
      context: .
