name: Publish container

on:
  push:
    branches: [ main, "release/**" ]
    tags: [ "v*" ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  publish:
    uses: project-unisonOS/unison-platform/.github/workflows/reusable-build.yml@d03a4a5cf6d6ac0e90ebbb09a886a6d7bbd772c6
    with:
      image_name: unison-storage
      domain: storage
      service_port: "8082"
    secrets: inherit
