name: Publish container

on:
  push:
    branches: [ main, "release/**" ]
    tags: [ "v*" ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  publish:
    uses: project-unisonOS/unison-platform/.github/workflows/reusable-build.yml@ea3ba32303bd4dc183d1086bb3208842cc64af43
    with:
      image_name: unison-storage
      domain: storage
      service_port: "8082"
    secrets: inherit
