name: Publish container

on:
  push:
    branches: [ main, "release/**" ]
    tags: [ "v*" ]

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write
  artifact-metadata: write
  security-events: write

jobs:
  publish:
    uses: project-unisonOS/unison-platform/.github/workflows/reusable-build.yml@ee1593dae7c003651890e66918aed47cb03db06d
    with:
      image_name: unison-storage
      domain: storage
      service_port: "8082"
    secrets: inherit
